### ISSUE TITLE
Command-line parameters require validation.

### ISSUE THREAD

**Issue by seancallaway** [seancallaway/PWGen#2]
The following code in the command-line script needs to be modified to confirm that the input is a positive integer. If it isn't, set num to 1.

``` python
if len(sys.argv) > 1:
        # TODO: error out if not a number
        num = int(sys.argv[1])
```

**Comment by seancallaway** [comment]
**Example of the problem:** 
```sh
$ nupass six
Traceback (most recent call last):
  File "/home/scallaway/.local/bin/nupass", line 27, in <module>
    main()
  File "/home/scallaway/.local/bin/nupass", line 20, in main
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'six'
```

We should also create tests for this, as well.
